{
 "title": "New dashboard yyp",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "DATAGRAND HBASE DASHBOARD",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "\n# 平台研发组 HBase Dashboard\n\n功能：统计HBase数据库具体数据的存储情况。\n\n\n\n\n\n",
   "targets": [
    {
     "rawSql": "SELECT\n  count_time AS \"time\",\n  id\nFROM hbasecnt\nWHERE\n  $__timeFilter(count_time)\nORDER BY count_time"
    }
   ]
  },
  {
   "title": "HBase 各表存储数据总量统计图",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  count_time AS \"time\",\n  count_value AS \"巨潮资讯网总量统计值\"\nFROM hbasecnt\nWHERE\n  tablename = \"cninfo\" AND\n  item = \"rowCntBase\"\nORDER BY count_time"
    },
    {
     "rawSql": "SELECT\n  count_time AS \"time\",\n  count_value AS \" 微信公众号总量统计值\"\nFROM hbasecnt\nWHERE\n  tablename = \"weixin\" AND\n  item = \"rowCntBase\"\nORDER BY count_time"
    },
    {
     "rawSql": "SELECT\n  count_time AS \"time\",\n  count_value AS \"裁判文书网总量统计值\"\nFROM hbasecnt\nWHERE\n  tablename = \"wenshu\" AND\n  item = \"rowCntBase\"\nORDER BY count_time"
    },
    {
     "rawSql": "SELECT\n  count_time AS \"time\",\n  count_value AS \"Kafka总量统计值\"\nFROM hbasecnt\nWHERE\n  tablename = \"kafka_op\" AND\n  item = \"rowCntBase\"\nORDER BY count_time"
    }
   ]
  },
  {
   "title": "HBase 各表存储数据增量统计图 ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  count_time AS \"time\",\n  count_value AS \"巨潮资讯网增量统计值\"\nFROM hbasecnt\nWHERE\n  tablename = 'cninfo' AND\n  item = 'rowCntDeta'\nORDER BY count_time"
    },
    {
     "rawSql": "SELECT\n  count_time AS \"time\",\n  count_value AS \"微信公众号增量统计值\"\nFROM hbasecnt\nWHERE\n  tablename = 'weixin' AND\n  item = 'rowCntDeta'\nORDER BY count_time"
    },
    {
     "rawSql": "SELECT\n  count_time AS \"time\",\n  count_value AS \"裁判文书网增量统计值\"\nFROM hbasecnt\nWHERE\n  tablename = 'wenshu' AND\n  item = 'rowCntDeta'\nORDER BY count_time"
    },
    {
     "rawSql": "SELECT\n  count_time AS \"time\",\n  count_value AS \"Kakfa增量统计值\"\nFROM hbasecnt\nWHERE\n  tablename = 'kafka_op' AND\n  item = 'rowCntDeta'\nORDER BY count_time"
    }
   ]
  },
  {
   "title": "网页库总表中各网站爬取总量统计图",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  count_time AS \"time\",\n  count_value AS \"投资界官网爬取总量统计值\"\nFROM sparkstatistic\nWHERE\n  tablename = \"webtable\" AND\n  item = \"RowKeyBase\" AND\n  filter_condition = \"cn.pedaily\"\nORDER BY count_time"
    },
    {
     "rawSql": "SELECT\n  count_time AS \"time\",\n  count_value AS \"东方财富网爬取总量统计值\"\nFROM sparkstatistic\nWHERE\n  tablename = \"webtable\" AND\n  item = \"RowKeyBase\" AND\n  filter_condition = \"com.eastmoney\"\nORDER BY count_time"
    },
    {
     "rawSql": "SELECT\n  count_time AS \"time\",\n  count_value AS \"金融界爬取总量统计值\"\nFROM sparkstatistic\nWHERE\n  tablename = \"webtable\" AND\n  item = \"RowKeyBase\" AND\n  filter_condition = \"cn.com.jrj\"\nORDER BY count_time"
    },
    {
     "rawSql": "SELECT\n  count_time AS \"time\",\n  count_value AS \"中国金融科技企业数据库爬取总量统计值\"\nFROM sparkstatistic\nWHERE\n  tablename = \"webtable\" AND\n  item = \"RowKeyBase\" AND\n  filter_condition = \"cn.fintechdb\"\nORDER BY count_time"
    },
    {
     "rawSql": "SELECT\n  count_time AS \"time\",\n  count_value AS \"好大夫爬取总量统计值\"\nFROM sparkstatistic\nWHERE\n  tablename = \"webtable\" AND\n  item = \"RowKeyBase\" AND\n  filter_condition = \"com.haodf\"\nORDER BY count_time"
    },
    {
     "rawSql": "SELECT\n  count_time AS \"time\",\n  count_value AS \"参考消息爬取总量统计值\"\nFROM sparkstatistic\nWHERE\n  tablename = \"webtable\" AND\n  item = \"RowKeyBase\" AND\n  filter_condition = \"com.cankaoxiaoxi\"\nORDER BY count_time"
    },
    {
     "rawSql": "SELECT\n  count_time AS \"time\",\n  count_value AS \"简书爬取总量统计值\"\nFROM sparkstatistic\nWHERE\n  tablename = \"webtable\" AND\n  item = \"RowKeyBase\" AND\n  filter_condition = \"com.jianshu\"\nORDER BY count_time"
    },
    {
     "rawSql": "SELECT\n  count_time AS \"time\",\n  count_value AS \"肆客足球爬取总量统计值\"\nFROM sparkstatistic\nWHERE\n  tablename = \"webtable\" AND\n  item = \"RowKeyBase\" AND\n  filter_condition = \"cn.qiuduoduo\"\nORDER BY count_time"
    },
    {
     "rawSql": "SELECT\n  count_time AS \"time\",\n  count_value AS \"虎嗅网爬取总量统计值\"\nFROM sparkstatistic\nWHERE\n  tablename = \"webtable\" AND\n  item = \"RowKeyBase\" AND\n  filter_condition = \"com.huxiu\"\nORDER BY count_time"
    },
    {
     "rawSql": "SELECT\n  count_time AS \"time\",\n  count_value AS \"中国证券监督管理委员会网爬取总量统计值\"\nFROM sparkstatistic\nWHERE\n  tablename = \"webtable\" AND\n  item = \"RowKeyBase\" AND\n  filter_condition = \"cn.gov.csrc\"\nORDER BY count_time"
    }
   ]
  },
  {
   "title": " 网页库总表中各网站爬取增量统计图 ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  count_time AS \"time\",\n  count_value AS \"投资界爬取增量统计值\"\nFROM sparkstatistic\nWHERE\n  $__timeFilter(count_time) AND\n  tablename = \"webtable\" AND\n  item = \"RowKeyDeta\" AND\n  filter_condition = \"cn.pedaily\"\nORDER BY count_time"
    },
    {
     "rawSql": "SELECT\n  count_time AS \"time\",\n  count_value AS \"东方财富网爬取增量统计值\"\nFROM sparkstatistic\nWHERE\n  $__timeFilter(count_time) AND\n  tablename = \"webtable\" AND\n  item = \"RowKeyDeta\" AND\n  filter_condition = \"com.eastmoney\"\nORDER BY count_time"
    },
    {
     "rawSql": "SELECT\n  count_time AS \"time\",\n  count_value AS \"金融界爬取增量统计值\"\nFROM sparkstatistic\nWHERE\n  $__timeFilter(count_time) AND\n  tablename = \"webtable\" AND\n  item = \"RowKeyDeta\" AND\n  filter_condition = \"cn.com.jrj\"\nORDER BY count_time"
    },
    {
     "rawSql": "SELECT\n  count_time AS \"time\",\n  count_value AS \"中国金融科技企业数据库爬取增量统计值\"\nFROM sparkstatistic\nWHERE\n  $__timeFilter(count_time) AND\n  tablename = \"webtable\" AND\n  item = \"RowKeyDeta\" AND\n  filter_condition = \"cn.fintechdb\"\nORDER BY count_time"
    },
    {
     "rawSql": "SELECT\n  count_time AS \"time\",\n  count_value AS \"好大夫爬取增量统计值\"\nFROM sparkstatistic\nWHERE\n  $__timeFilter(count_time) AND\n  tablename = \"webtable\" AND\n  item = \"RowKeyDeta\" AND\n  filter_condition = \"com.haodf\"\nORDER BY count_time"
    },
    {
     "rawSql": "SELECT\n  count_time AS \"time\",\n  count_value AS \"参考消息爬取增量统计值\"\nFROM sparkstatistic\nWHERE\n  $__timeFilter(count_time) AND\n  tablename = \"webtable\" AND\n  item = \"RowKeyDeta\" AND\n  filter_condition = \"com.cankaoxiaoxi\"\nORDER BY count_time"
    },
    {
     "rawSql": "SELECT\n  count_time AS \"time\",\n  count_value AS \"简书爬取增量统计值\"\nFROM sparkstatistic\nWHERE\n  $__timeFilter(count_time) AND\n  tablename = \"webtable\" AND\n  item = \"RowKeyDeta\" AND\n  filter_condition = \"com.jianshu\"\nORDER BY count_time"
    },
    {
     "rawSql": "SELECT\n  count_time AS \"time\",\n  count_value AS \"肆客足球爬取增量统计值\"\nFROM sparkstatistic\nWHERE\n  $__timeFilter(count_time) AND\n  tablename = \"webtable\" AND\n  item = \"RowKeyDeta\" AND\n  filter_condition = \"cn.qiuduoduo\"\nORDER BY count_time"
    },
    {
     "rawSql": "SELECT\n  count_time AS \"time\",\n  count_value AS \"虎嗅网爬取增量统计值\"\nFROM sparkstatistic\nWHERE\n  $__timeFilter(count_time) AND\n  tablename = \"webtable\" AND\n  item = \"RowKeyDeta\" AND\n  filter_condition = \"com.huxiu\"\nORDER BY count_time"
    },
    {
     "rawSql": "SELECT\n  count_time AS \"time\",\n  count_value AS \"中国证券监督管理委员会网爬取增量统计值\"\nFROM sparkstatistic\nWHERE\n  $__timeFilter(count_time) AND\n  tablename = \"webtable\" AND\n  item = \"RowKeyDeta\" AND\n  filter_condition = \"cn.gov.csrc\"\nORDER BY count_time"
    }
   ]
  }
 ]
}